### ISSUE TITLE
[BUG] Bad reading of the processor model

### ISSUE THREAD

**Issue by dompiotr85** [ncs-sniper/Lib.SimpleCPUID#1]
Hi František,

I have found that there is a bug in wrong interpretation of readings of CPUID processor model in Lib.SimpleCPUID.

According to Intel's CPUID information to read processor model properly there need to be done this operation:

`IF (Family_ID = 06H or Family_ID = 0FH)`
`THEN DisplayModel = (Extended_Model_ID « 4) + Model_ID;`
`(* Right justify and zero-extend 4-bit field; display Model_ID as HEX field.*)`
`ELSE DisplayModel = Model_ID;`
`FI;`
`(* Show DisplayModel as HEX field. *)`

and in Lib.SimpleCPUID unit code this operation is made different:

`// processor model`
`    If GetBits(fLeafs[Index].Data.EAX,8,11) in [$6,$F] then`
`      fInfo.ProcessorModel := (GetBits(fLeafs[Index].Data.EAX,16,19) shr 4) or`
`                                    GetBits(fLeafs[Index].Data.EAX,4,7)`
`    else`
`      fInfo.ProcessorModel := GetBits(fLeafs[Index].Data.EAX,4,7);`

This bug causes the processor model to be calculated incorrectly. Based upon Intel's specification this calculation should look like this:

`// processor model`
`    If GetBits(fLeafs[Index].Data.EAX,8,11) in [$6,$F] then`
`      fInfo.ProcessorModel := (GetBits(fLeafs[Index].Data.EAX,16,19) shl 4) +`
`                                    GetBits(fLeafs[Index].Data.EAX,4,7)`
`    else`
`      fInfo.ProcessorModel := GetBits(fLeafs[Index].Data.EAX,4,7);`

My solution for this bug is a this small change in Lib.SimpleCPUID which fix this bug.

In addition, Intel suggest that processor model should be displayed in hexadecimal value. I have done small Test program that use Lib.SimpleCPUID with my fix already applied and compared results with processor model value extracted from [Intel(R) Processor Identification Utility application](https://downloadcenter.intel.com/download/7838/Intel-Processor-Identification-Utility-Windows-Version) which is available for free on Intel's webpage. The comparison was identical proving that fix is working. I am attaching this Test program as well as 3 images with my CPU comparison with Intel's application and www.cpu-world.com CPUID result.

[SimpleCPUID.Fix.zip](https://github.com/ncs-sniper/Lib.SimpleCPUID/files/2364225/SimpleCPUID.Fix.zip)
[SimpleCPUID.Fix.Proof.zip](https://github.com/ncs-sniper/Lib.SimpleCPUID/files/2364226/SimpleCPUID.Fix.Proof.zip)

My best regards,
Piotr Domański

**Comment by ncs-sniper** [comment]
You are right about the shift in calculation, it was simple mistake that I have missed in testing because of hardware I was testing on.
As for the representation - this library was never ment for displaying info to the user, only for internal use in other programs, so I have not even considered format.

**Comment by ncs-sniper** [comment]
Changes merged, I am closing this issue.
Many thanks for reporting the error!
